
-- Add status column to orders
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'status') THEN
        ALTER TABLE orders ADD COLUMN status TEXT DEFAULT 'placed';
    END IF;
END $$;

-- Create order_status_logs table
CREATE TABLE IF NOT EXISTS order_status_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES orders(id),
    status TEXT NOT NULL,
    updated_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
